src/Terrarium.Server/Models/Usage.cs
using System;

namespace Terrarium.Server.Models
{
    public class Usage
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public string Domain { get; set; }
        public DateTime TickTime { get; set; }
        public int UsageMinutes { get; set; }
        public string IPAddress { get; set; }
        public string GameVersion { get; set; }
        public string PeerChannel { get; set; }
        public int PeerCount { get; set; }
        public int AnimalCount { get; set; }
        public int MaxAnimalCount { get; set; }
        public int WorldHeight { get; set; }
        public int WorldWidth { get; set; }
        public string MachineName { get; set; }
        public string OSVersion { get; set; }
        public int ProcessorCount { get; set; }
        public string ClrVersion { get; set; }
        public int WorkingSet { get; set; }
        public int MaxWorkingSet { get; set; }
        public int MinWorkingSet { get; set; }
        public int ProcessorTime { get; set; }
        public DateTime ProcessStartTime { get; set; }
    }
}

src/Terrarium.Server/ViewModels/UsageViewModel.cs
namespace Terrarium.Server.ViewModels
{
    public class UsageViewModel
    {
        public string UserAliasLabel { get; set; }
        public string UserTodayLabel { get; set; }
        public string UserWeekLabel { get; set; }
        public string UserTotalLabel { get; set; } 
    }
}

src/Terrarium.Server/Controllers/ChartController.cs
using System.Collections.Generic;
using System.Web.Http;
using Terrarium.Server.Models;

namespace Terrarium.Server.Controllers
{
    /// <summary>
    /// The chart service is capable of providing remote clients
    /// with charting data by calling on the local charting components to
    /// generate the chart and then returning any required information to the
    /// remote client to display the chart.  This service is also capable of
    /// returning all the data required to produce a remote interface to
    /// graph generation and the information required to generate top-n reports.
    /// </summary>
    public class ChartController : ApiController
    {
        /// <summary>
        /// Returns a graph of ALL species along with their latest
        /// point of population data.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("api/charts/species")]
        public IEnumerable<object> Species()
        {
            return null;
        }

        /// <summary>
        /// Returns the latest datapoint of statistics information
        /// for a given species in the form of a dataset.
        /// </summary>
        /// <param name="species"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("api/charts/species/{species}")]
        public IEnumerable<object> GrabLatestSpeciesData(string species)
        {
            return null;
        }

        /// <summary>
        /// Returns various information about the top-num animals
        /// of a given organism type for use in top-n reporting.
        /// </summary>
        /// <param name="version"></param>
        /// <param name="tat"></param>
        /// <param name="num"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("api/charts/animals/top")]
        public IEnumerable<object> GetTopAnimals(string version, OrganismType tat, int num)
        {
            return null;
        }
    }
}

src/Terrarium.Server/Controllers/HomeController.cs
using System.Data.Entity;
using System.Web.Mvc;
using Terrarium.Server.DataModels;
using Terrarium.Server.Models;
using Terrarium.Server.Repositories;
using Terrarium.Server.ViewModels;

namespace Terrarium.Server.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITipRepository _tipRepository;
        private readonly IUsageRepository _usageRepository;

        public HomeController(ITipRepository tipRepository, IUsageRepository usageRepository)
        {
            _tipRepository = tipRepository;
            _usageRepository = usageRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Charts()
        {
            return View();
        }

        public ActionResult Usage()
        {
            var alias = Request.QueryString["Alias"] ?? User.Identity.Name;

            var vm = new UsageViewModel
            {
                UserAliasLabel = alias,
                UserTodayLabel = _usageRepository.GetUserUsage(alias, UsagePeriod.Today).TotalHours + " hours",
                UserWeekLabel = _usageRepository.GetUserUsage(alias, UsagePeriod.Week).TotalHours + " hours",
                UserTotalLabel = _usageRepository.GetUserUsage(alias, UsagePeriod.Total).TotalHours + " hours"
            };

            return View(vm);
        }

        public ActionResult RandomTip()
        {
            var tip = _tipRepository.GetRandomTip();
            return PartialView("_RandomTips", new RandomTipViewModel {Tip = tip.Tip});
        }

        public ActionResult ServerStatus()
        {
            // hack fix me
            var api = new PeerDiscoveryController(new TerrariumDbContext());

            var vm = new ServerStatusViewModel
            {
                IsDatabaseUp = Database.Exists("TerrariumDbContext"),
                PeerCount = api.GetNumPeers("", "")
            };

            return PartialView("_ServerStatus", vm);
        }

        public ActionResult TopCritters()
        {
            return PartialView("_TopCritters");
        }
    }
}

src/Terrarium.Server/Controllers/UsageController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Terrarium.Server.DataModels;
using Terrarium.Server.Infrastructure;
using Terrarium.Server.Models;

namespace Terrarium.Server.Controllers
{
    /// <summary>
    /// Reports on usage of the system.
    /// </summary>
    public class UsageController : ApiController
    {
        private readonly ITerrariumDbContext _context;

        public UsageController(ITerrariumDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// <para>
        /// Allows a client to report its own usage statistics and adds it to the system.
        /// </para>
        /// <para>
        /// The IPAddress portion of the UsageData object is automatically filled in by the server.
        /// </para>
        /// <para>
        /// Usage reporting is only allowed once every 60 minutes from a client.</para>
        /// </summary>
        /// <param name="data">UsageData from the client about the current state of their Terrarium.</param>
        [HttpPost]
        [Route("api/usage")]
        public HttpResponseMessage ReportUsage(Usage data)
        {
            if (data == null)
            {
                throw new HttpResponseException(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.BadRequest,
                    Content = new StringContent("No usage data provided")
                });
            }

            try
            {
                data.IPAddress = RequestHelpers.GetClientIpAddress(Request);
                _context.AddUsage(data);
            }
            catch (Exception e)
            {
                throw new HttpResponseException(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.InternalServerError,
                    Content = new StringContent(e.Message)
                });
            }

            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}

src/Terrarium.Server/Views/Home/Charts.cshtml
@{
    ViewBag.Title = "Charts";
}

<h2>Charts</h2>

src/Terrarium.Server/Views/Home/Framework.cshtml
@{
    ViewBag.Title = "Framework";
}

<h2>Framework</h2>

src/Terrarium.Server/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>Terrarium Server</h1>
    <p class="lead">Terrarium provides a great way for developers to learn about the .NET programming model and language as they develop creatures and introduce them into a peer-to-peer ecosystem.</p>
    <p>
        <a href="http://terrarium.azurewebsites.net/" class="btn btn-primary btn-lg">Learn more &raquo;</a>
        <a href="https://www.nuget.org/packages/Terrarium.Sdk/"><img src="@Url.Content("~/Images/nuget.png")" alt="" /></a>
        <a href="https://github.com/terrariumapp"><img src="@Url.Content("~/Images/github.png")" alt="Fork us on GitHub" /></a>
    </p>
</div>

<!-- layout blatently stolen from http://www.west-wind.com/westwind.applicationconfiguration/ Hi Rick! -->

<div class="row">
    <div class="col-lg-6">
        <h2>Learn</h2>
        <p>
            This site contains the live Terrarium Server that clients connect with via a RESTful API. Documentation for the API can be found <a href="~/swagger" target="_new">here</a>.
        </p>
        <p>
            Looking for developer documentation, background information, news, tips, strategies, or general help?
            Please visit <a href="http://terrarium.azurewebsites.net/">the main site here</a>.
        </p>
    </div>
    <div class="col-lg-6">
        <h2>Stats</h2>
        <p>Terrarium Server tracks all aspects of all organisms in the system. Who's the top bug, fasted moving, etc. so you can check it all out here.</p>
        <p>You can use this page to track your own creations usage statistics, or see what the compeition is up to. Check it out @Html.ActionLink("now", "Usage", "Home")!</p>
    </div>
</div>

src/Terrarium.Server/Views/Home/Usage.cshtml
@model Terrarium.Server.ViewModels.UsageViewModel

@{
    ViewBag.Title = "Usage";
}

<h2>Usage Summary</h2>

<table class="table">
    <tr>
        <td colspan="6">Below are the statistics for you.</td>
    </tr>
    <tr>
        <td colspan="6"><b>Your Statistics (@Model.UserAliasLabel)</b></td>
    </tr>
    <tr>
        <td>Today's Hours</td>
        <td>@Model.UserTodayLabel</td>
        <td>This Week's Hours</td>
        <td>@Model.UserWeekLabel</td>
        <td>Total Hours</td>
        <td>@Model.UserTotalLabel</td>
    </tr>
</table>

<table class="table">
    <tr>
        <td>
            <h2>Top 10 Participants</h2>
        </td>
        <td>
            <div class="pull-right">
                <b>Period</b>
                <ul class="nav nav-pills">
                    <li><a href="#">Today</a></li>
                    <li class="active"><a href="#">Week</a></li>
                    <li><a href="#">Total</a></li>
                </ul>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            These are the top 10 participants based on total hours that they have run Terrarium. Use the buttons above to choose which period to view.
        </td>
    </tr>
    <tr>
        <td colspan="2">
            
@*            <asp:DataGrid CellPadding="4" GridLines="None" Width="100%" ID="individualDataGrid" runat="server" AutoGenerateColumns="False" EnableViewState="False">*@
@*                <itemstyle horizontalalign="Left" verticalalign="Middle" font-size="0.75em" backcolor="White" forecolor="Black" />*@
@*                <alternatingitemstyle horizontalalign="Left" verticalalign="Middle" font-size="0.75em" backcolor="#F0F0F0" forecolor="Black" />*@
@*                <columns>*@
@*                    <asp:templatecolumn headertext="Rank">*@
@*                        <headerstyle width="64px" />*@
@*                        <itemtemplate>*@
@*                            <span><%# (Container.DataSetIndex + 1).ToString() %></span>*@
@*                        </itemtemplate>*@
@*                    </asp:templatecolumn>*@
@*                    <asp:templatecolumn>*@
@*                        <headertemplate>*@
@*                            Alias*@
@*                        </headertemplate>*@
@*                        <headerstyle font-bold="True" />*@
@*                        <itemtemplate>*@
@*                            <span><%# GetUserUsageSummary(Container.DataItem).Alias%></span>*@
@*                        </itemtemplate>*@
@*                    </asp:templatecolumn>*@
@*                    <asp:templatecolumn>*@
@*                        <headertemplate>*@
@*                            Hours*@
@*                        </headertemplate>*@
@*                        <headerstyle cssclass="TypeGridNameHeader" width="96px" />*@
@*                        <itemtemplate>*@
@*                            <span><%# GetUserUsageSummary(Container.DataItem).TotalHours%></span>*@
@*                        </itemtemplate>*@
@*                    </asp:templatecolumn>*@
@*                </columns>*@
@*                <headerstyle backcolor="#808080" font-bold="True" font-size="0.75em" forecolor="White"*@
@*                             horizontalalign="Left" verticalalign="Middle" />*@
@*            </asp:DataGrid>*@
        </td>
    </tr>
</table>